### ISSUE TITLE
node selector injection feature doesn't work when ResourceName is not defined in NAD

### ISSUE THREAD

**Issue by martinkennelly** [k8snetworkplumbingwg/network-resources-injector#78]
Hey,
During e2e testing, we noticed that node selector injection doesn't work when ```resourceName``` is not defined in the NAD.
Works fine when there is an additional network defined.
I believe a use case was when no additional network was defined. i.e. [macvlan](https://github.com/k8snetworkplumbingwg/network-resources-injector/pull/21#issuecomment-597936699)
Documentation example for readme: #50 
Original PR: #21 
@pperiyasamy 

Node selector injection feature works:
```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: foo-network
  annotations:
    k8s.v1.cni.cncf.io/nodeSelector: kubernetes.io/hostname=kind-worker2
    k8s.v1.cni.cncf.io/resourceName: example.com/foo
spec:
...
```

Node selector injection feature doesnt work:
```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: foo-network
  annotations:
    k8s.v1.cni.cncf.io/nodeSelector: kubernetes.io/hostname=kind-worker2
spec:
...
```

Sample Macvlan NAD with no ```resourceName``` defined:
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec: 
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {
                "dst": "0.0.0.0/0",
                "gw": "10.1.1.1"
              }
            ] 
          }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'
```
