### ISSUE TITLE
'User defined injections' feature does not react on ConfigMap remove

### ISSUE THREAD

**Issue by MichalGuzieniuk** [k8snetworkplumbingwg/network-resources-injector#86]
**Problem:**
After ConfigMap removal labels defined in the POD specification are read by NRI and still processed. In result, annotations are updated even if I as a user does not expect such behaviour.

**Test steps:**
As a precondition NRI is setup, and all networks are available.
1. Add network attachment definitions
2. Add ConfigMap
3. Wait 1 minute - time needed to update POD and NRI
4. Create POD - verify that annotations were changed according to labels (k8s.v1.cni.cncf.io/networks: sriov-net-attach-def)
5. Delete POD
6. Delete ConfigMap
7. Wait 1 minute - time needed to update POD and NRI
8. Create POD - verify that annotation were not changed, even if POD specification defines label.
**Expected annotation k8s.v1.cni.cncf.io/networks: foo-network
Actual annotation k8s.v1.cni.cncf.io/networks: sriov-net-attach-def**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-user-defined-injections
  namespace: kube-system
data:
  "customInjection": '{"op": "add", "path": "/metadata/annotations", "value": {"k8s.v1.cni.cncf.io/networks": "sriov-net-attach-def"}}'
```

```
apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    customInjection: "true"
  annotations:
    k8s.v1.cni.cncf.io/networks: foo-network
spec:
  containers:
  - name: app
    image: alpine
    command: [ "/bin/sh", "-c", "sleep INF" ]
```

```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: foo-network
  annotations:
    k8s.v1.cni.cncf.io/resourceName: example.com/foo
spec:
  config: |
    {
      "cniVersion": "0.3.0",
      "name": "foo-network",
      "type": "loopback"
    }
```

```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net-attach-def
  # namespace: kube-system
  annotations:
    k8s.v1.cni.cncf.io/resourceName: example.com/boo
spec:
  config: |
    {
      "cniVersion": "0.3.0",
      "name": "sriov-net-attach-def",
      "type": "loopback"
    }

```
